title: Prateek Mukherjee
logo: /assets/img/prateek.jpeg
description: Innovative and results-driven Machine learning Engineer with a specialization in Big Data Analytics, looking for opportunity in the field of Data Analysis and Artificial Intelligence.  
#show_downloads: true
is_user_page: ""
theme: jekyll-theme-minimal
